name: 'nextgen-ai-3'

services:
  sveltekit:
    build: .
    container_name: nextgen-ai-3-sveltekit
    volumes:
      - ./databases/postgres/socket:/var/run/postgresql
      - ./files:/app/files
    ports:
      - 5173:5173
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    healthcheck:
      test: ['CMD', '/nodejs/bin/node', '/app/health-check.mjs']
      start_period: 10s
      start_interval: 1s
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: nextgen-ai-3-postgres
    volumes:
      - ./databases/postgres/socket:/var/run/postgresql
      - ./databases/postgres/data:/var/lib/postgresql/data
      - ./databases/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./databases/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command:
      [
        'postgres',
        '-c',
        'config_file=/etc/postgresql/postgresql.conf',
        '-c',
        'hba_file=/etc/postgresql/pg_hba.conf'
      ]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nextgen-ai-3}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-nextgen-ai-3}
    shm_size: 4GB
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${POSTGRES_USER:-postgres}',
          '-d',
          '${POSTGRES_DB:-nextgen-ai-3}'
        ]
      start_period: 10s
      start_interval: 1s
    restart: unless-stopped
