import difflib from 'difflib';

const s1 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et nisl a sapien elementum cursus. Mauris ut tortor sit amet velit blandit euismod. Ut mauris enim, maximus quis lorem at, scelerisque pharetra ligula. Nunc mauris odio, pharetra vel odio nec, ornare vestibulum velit. Fusce vitae eleifend eros, ac consequat est. Aliquam erat volutpat. Proin non odio eros. Etiam massa libero, tempor vestibulum massa a, cursus egestas elit. Donec eu bibendum velit. In hac habitasse platea dictumst. Suspendisse ultrices enim a laoreet aliquet. Morbi iaculis elementum est, quis vulputate sem dapibus eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas iaculis purus nunc, at placerat lacus consequat et.

Curabitur id sollicitudin dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In id magna eu sem tempus blandit. Quisque a risus velit. Proin et egestas mi. Vestibulum rhoncus ac mauris sit amet viverra. Ut dignissim leo id felis vehicula, non iaculis erat mattis. Nullam luctus augue sit amet sem egestas sodales. Maecenas tincidunt urna felis, eu laoreet mauris consequat vitae. Aenean dignissim mauris ligula, vel faucibus nulla sollicitudin ac. Sed a purus a tellus ultrices commodo. Pellentesque tempor mi sollicitudin justo faucibus, et molestie purus molestie. Nam nec hendrerit erat, vitae convallis eros. Quisque pretium vitae metus at pellentesque. In dictum, augue eu porttitor elementum, nisl tortor tristique metus, eget tristique nibh ligula nec nisl. Nam blandit egestas pellentesque.

Proin justo nibh, tempor sed faucibus sit amet, pellentesque eu nunc. Suspendisse vitae enim sed turpis mollis scelerisque eget ut justo. Cras risus urna, mollis in nunc id, bibendum bibendum quam. In ut mauris sit amet lacus lobortis tincidunt. Nam enim lacus, elementum non libero at, dictum finibus dolor. Integer dapibus fermentum vestibulum. Suspendisse laoreet bibendum scelerisque. Quisque commodo mi erat. Aenean sagittis elit sed lectus commodo gravida non vitae sem. Etiam feugiat placerat vestibulum. Sed vulputate at justo vel congue. Aliquam non nisl a augue iaculis malesuada a egestas sem. Donec lobortis leo tortor. Nulla facilisi. Sed in diam elementum, blandit est eget, faucibus tortor. Duis vestibulum elementum odio, sit amet convallis ipsum iaculis id.

Proin vestibulum porttitor urna ut volutpat. Pellentesque purus ligula, condimentum facilisis arcu consectetur, viverra placerat orci. Curabitur accumsan faucibus massa a tincidunt. Maecenas quis pretium mauris. Morbi volutpat, est tincidunt pellentesque feugiat, quam erat ultrices elit, quis tempor elit lorem pulvinar risus. Morbi mattis eu nunc ut scelerisque. Donec eros metus, interdum id accumsan non, euismod ut lorem. Duis a mauris leo.

Proin dapibus eros lacus, et pharetra sapien aliquet lobortis. Nam vestibulum in nisl at posuere. Quisque ac eros ultricies, viverra elit id, luctus risus. Proin nec aliquet dui, nec dapibus nisl. Nam sit amet malesuada ligula. Aenean maximus odio sed arcu finibus, a tincidunt quam porttitor. Curabitur ac ligula a arcu porttitor malesuada. Suspendisse gravida justo sit amet ex mollis, sit amet ultricies justo varius. Vestibulum ornare diam sed nunc lacinia bibendum. In facilisis, magna et pulvinar tincidunt, diam sem viverra dolor, vel mollis orci odio tincidunt risus. Pellentesque bibendum vulputate lectus, nec dapibus tortor vestibulum nec. Donec luctus massa vel justo dignissim, quis vulputate elit cursus. Praesent ac tortor venenatis, convallis lectus eu, convallis turpis.`;

const s2 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quis congue nunc. Cras lobortis faucibus maximus. Nulla facilisi. Suspendisse nulla velit, scelerisque maximus condimentum eu, tincidunt eu risus. Nullam et eleifend mi, et euismod mi. Vestibulum eu mi at nunc bibendum vehicula. Etiam eleifend urna in massa feugiat dapibus. Etiam convallis massa id est rhoncus convallis. Maecenas sagittis mauris quis sollicitudin eleifend. Cras ullamcorper sapien et neque facilisis fermentum. Maecenas quis vestibulum massa. Nam eget egestas odio. Suspendisse potenti. Integer suscipit, nulla eget lacinia cursus, sapien mauris tempus nisl, ut finibus magna tortor ut sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi quis diam eu enim porta congue a sed mi.

Suspendisse potenti. Pellentesque pharetra risus a placerat faucibus. Nullam accumsan consectetur enim id lobortis. Nam ultricies nibh eu dui sollicitudin, id vestibulum urna iaculis. Sed et dapibus nisl. Nulla at fermentum risus. Nam a diam quis mauris pellentesque bibendum ac quis risus. Duis condimentum interdum dui, sed mattis magna fermentum et. Aenean vel justo tristique, venenatis dolor vel, lobortis nunc. Sed commodo, arcu sit amet ornare volutpat, velit erat feugiat justo, vel pretium sem arcu eget ipsum. Aenean tempus vulputate ante vel fringilla. Donec bibendum orci et orci mattis feugiat. Phasellus in sapien orci.

Donec vel neque eu odio interdum convallis. Mauris non nibh consequat, laoreet augue et, ullamcorper mauris. Quisque sollicitudin justo velit, id posuere diam varius quis. Integer ornare ipsum eros, sit amet sagittis dui malesuada sed. Donec egestas sapien a nisi porta, ac sagittis magna cursus. Aenean vehicula id justo eget tristique. Aliquam hendrerit mauris ut eros ultrices pulvinar. Nam a vehicula arcu, ac pulvinar ante. Sed vehicula nisi at augue gravida, in dapibus nunc facilisis. Nulla dignissim rhoncus lorem. Proin sagittis sapien nec neque lacinia mollis. Phasellus feugiat ultrices nisi quis ultricies. Curabitur placerat eleifend tincidunt. In vulputate lorem et velit aliquet ultrices ut sed ipsum. Pellentesque lorem ex, viverra bibendum suscipit nec, tempor et lectus.

Phasellus vehicula ut ante eget tincidunt. Ut porttitor nec lacus dapibus pharetra. Curabitur mollis scelerisque eros, ac suscipit enim interdum quis. Nullam auctor egestas libero quis pellentesque. Nunc fringilla dolor ut enim gravida faucibus. Maecenas semper mauris in blandit condimentum. Nulla libero turpis, volutpat ac tempus sit amet, dapibus non nisi. Mauris lacinia odio eget tellus suscipit convallis. Donec laoreet, massa eget dictum bibendum, quam augue suscipit nisi, at euismod tellus lorem vel erat. Nunc viverra quam eleifend nulla convallis, eget tristique diam consectetur. Vivamus malesuada nisi in mi faucibus convallis. Nullam sodales pretium nisi vitae malesuada.

Aliquam felis arcu, eleifend at nibh nec, rutrum aliquam magna. Vestibulum efficitur faucibus lectus ut ornare. Nunc aliquam est metus, sed ullamcorper risus vehicula a. Sed vel massa eget massa rutrum maximus eu non massa. In luctus ipsum ut sodales ullamcorper. Quisque sit amet turpis efficitur, pharetra nibh ac, fringilla velit. Nulla facilisi. Proin venenatis tortor eget euismod efficitur. Curabitur tincidunt nisl sit amet nibh elementum ornare. In sit amet dapibus arcu. Phasellus risus elit, pulvinar non erat id, sollicitudin placerat sem. Praesent aliquam volutpat condimentum. Proin eleifend ut dolor in luctus. Sed ornare gravida molestie. In nisl sapien, finibus nec turpis non, dignissim mollis sem.`;

const start = performance.now();
const sequenceMatcher = new difflib.SequenceMatcher(null, s1, s2);
const ratio = sequenceMatcher.realQuickRatio();
const end = performance.now();

console.log(ratio, end - start);
